# Uncomment the next line to define a global platform for your project

# platform :ios, '9.0'

target 'testLocation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

# Pods for testLocation
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'GeoFire',:git=>'https://github.com/firebase/geofire-objc.git'
end







